### PR TITLE
WIP: Dockerize it

### PR DESCRIPTION
**Pull request by SeanKilleen**
Figured we'd make it a little easier.

### CODE REVIEW

**Comment by SeanKilleen** [comment]
At this point, I'm seeing:

> selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
>   (unknown error: DevToolsActivePort file doesn't exist)

I think this is related to permissions and Chrome being able to spawn new windows. I'll look into it. I feel like we're getting pretty close.

**Comment by SeanKilleen** [comment]
At this point, it looks like we it might be mostly working but the script itself is failing on submission. Likely due to headless mode. Will look into troubleshooting it but any other input is welcome.

**Comment by ramblingjordan** [comment]
@SeanKilleen there is new code in the master branch that addresses some of the captcha issues. There is however a manual step where a user needs to farm recaptcha tokens. Can we find a way to integrate that into your docker image and still provide the prompt for the user?

Setup is a major pain point for people now so this would be very helpful

**Comment by ramblingjordan** [comment]
We have moved active development of the python bot to this repo: https://github.com/ramblingjordan/AbBOT-python

Could you please recreate your PR over there?

Thanks!

**Comment by SeanKilleen** [comment]
Happy to! I hope to do it today.

**Pull request closed without merging**
