### PR TITLE
Created a dict of zip codes separated by city to use dynamically with city and county.

### PR DESCRIPTION
**Pull request by ticet11**
Just little touches.

### CODE REVIEW

**Comment by ramblingjordan** [comment]
Thanks for this! Unfortunately we made a change to move the data to a separate file which breaks this fix.

Could I humbly ask you to pull the changes and re-integrate this? I'd do it myself but I'm just trying to keep my head above water on the flood of changes! (Too soon for 'flood' jokes?)

**Comment by ticet11** [comment]
I'll give it a shot!

**Comment by jacobmovingfwd** [comment]
Can you split out the phrase commits to a diff branch? They're good & distinct from the zip code work. 
I know it's all small stuff, but will make merging easier.

**Comment by ramblingjordan** [comment]
We have moved active development of the python bot to this repo: https://github.com/ramblingjordan/AbBOT-python

Could you please recreate your PR over there?

Thanks!

**Pull request closed without merging**
