### PR TITLE
Added instructions for linuxes

### PR DESCRIPTION
**Pull request by Fordi**
I wanted to run this off my RasPi cloud server, so I documented what I needed to do.

### CODE REVIEW

**Comment by elementalcollision** [comment]
excellent.  I have a couple of spare Pi 3B lying around that I could easily hook up to test run this.

**Comment by andria-dev** [comment]
I updated the README to match the latest version, including instructions for Linux. Let me know if there's something that needs to be added to the README.

**Comment by ramblingjordan** [comment]
@Fordi please see the note from @andria-dev, can we close this PR?

**Comment by ramblingjordan** [comment]
Closing as per note from @andria-dev
Thanks for your submission!

**Pull request closed without merging**
