### PR TITLE
Fast reCaptcha workaround, requests without Selenium

### LINKED ISSUE #8: Bypass the front-end?
Leaving for someone smarter than me, I'm not available right now.

Can't we bypass the front end and just make post calls directly to the form? Pretty sure it can be done a lot faster this way.

something like this (some quick copy/pastes):

```
import requests

url = 'https://prolifewhistleblower.com/wp-admin/admin-ajax.php'
myobj = {'somekey': 'somevalue'}

x = requests.post(url, data = myobj)

print(x.text)
```

```
POST / HTTPS/2.0
Host: https://prolifewhistleblower.com/wp-admin/admin-ajax.php
Content-Type: application/x-www-form-urlencoded
Content-Length: 13
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryBfSESmlOiCYwo4Oq
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36

------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="textarea-1"

test
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="text-1"

test
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="text-6"

test
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="text-2"

test
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="text-3"

test
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="text-4"

test
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="text-5"

test
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="checkbox-1[]"

no
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="g-recaptcha-response"

03AGdBq25mBrjaNVz36yhqcO9OcG4Bz8eudySKVmEsF1kb_EEwwsL-3eYGIFTiVwOWtb5lNkeVDVh9h06amhoKfuQE_yxGlBNoyJMQ1suCroTCh9pIEDDOExyxxiv9mYst7F9wshD1LjAEfYyCFT9GtQfAbf-TVREQo7A_XsDIyAONrG73DC7ge4xS4Lz1hKeLe5oEvkdAi3f8CvH7FoQ9R7-zuxbojqbqMDUVjf2l19J6UxD-t3mgCm58VhLk7mllEC5rgvXD_R7aoHxxrMIWtZfLYfPKmvS25iFJk5ENc8ZfxP8f7sNqY4xjcOgTrSVb70Up5j6uUzlLiCB8tJ9U5SVpioUmMhdfxIV1SNKV7YYZun18GjqX0foLYPTZecIoDGo1LkIH2A2Jz6dgbVlQWGBxryRGGXia3QCXDVNt74daFayMem2X6eElYhB7k_OhcuNEdWG-s5fiNwhnTA0nCSp_E2OMde30Qg
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="hidden-1"

~~~ip~~~
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="referer_url"

https://prolifewhistleblower.com/anonymous-form/
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="forminator_nonce"

9fe66bf390
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="_wp_http_referer"

/anonymous-form/
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="form_id"

26
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="page_id"

27
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="form_type"

default
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="current_url"

https://prolifewhistleblower.com/
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="render_id"

0
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="action"

forminator_submit_form_custom-forms
------WebKitFormBoundaryBfSESmlOiCYwo4Oq
Content-Disposition: form-data; name="input_11"


------WebKitFormBoundaryBfSESmlOiCYwo4Oq--
```

### PR DESCRIPTION
**Pull request by andria-dev**
Fixes #8

Please rerun `pip3 install -r requests.txt` when updating.

## Things left to do:
- [x] ~Add random data for the sign up page.~ I'll leave that up to someone else.
- [x] Copy all generated data stuff from sc.js to data.py
- [x] Add generated data to data parameter in requests
- [x] Modify `/etc/hosts` and `C:\Windows\System32\drivers\etc\hosts` to redirect traffic to target domain to 127.0.0.1, this is necessary to allow reCaptcha to believe we are still on the target's website.
- [x] Figure out how to get updated nonce from website
- [x] Update README with new instructions

### CODE REVIEW

**Comment by andria-dev** [comment]
This PR is not totally finished, any comments are welcome though

**Comment by pastram-i** [comment]
I'll be available to work on this later today hopefully, ty for providing the captcha solution

**Comment by alicialynnlee** [comment]
any thoughts on putting the data in different files and importing it? ex `from cities.py import cities`

**Comment by andria-dev** [comment]
@alicialynnlee I was actually just thinking about this. I think that we should put the data in `.json` files and get the data from those files.

**Pull request merged**
